# Cloud Build: Web app — build (with NEXT_PUBLIC_API_URL), push to Artifact Registry, deploy to Cloud Run
# Run from repo root: gcloud builds submit . --config=apps/web/cloudbuild.yaml
#
# Pass the API URL at build time (required for Next.js client bundle):
#   gcloud builds submit . --config=apps/web/cloudbuild.yaml --substitutions=_NEXT_PUBLIC_API_URL=https://api-xxx.run.app
#
# Substitution variables (optional):
#   _REGION                 — e.g. asia-south1 (default below)
#   _REPO_NAME              — Artifact Registry repo name (default: tofa-repo)
#   _NEXT_PUBLIC_API_URL    — Public API URL for the frontend (must be set for production)

substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'tofa-repo'
  _NEXT_PUBLIC_API_URL: ''

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the Web Docker image with NEXT_PUBLIC_API_URL baked in (context = repo root)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-web'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.web'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-web'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'
    waitFor: ['build-web']

  # Deploy to Cloud Run (Service: web)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-web'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'web'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '${PROJECT_ID}'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'
    waitFor: ['push-web']

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:latest'
