# Cloud Build: Backend API — build, push to Artifact Registry, deploy to Cloud Run
# Run from repo root: gcloud builds submit . --config=apps/api/cloudbuild.yaml
#
# Substitution variables (optional):
#   _REGION     — e.g. asia-south1 (default below)
#   _REPO_NAME  — Artifact Registry repo name (default: tofa-repo)

substitutions:
  _REGION: 'asia-south1'
  _REPO_NAME: 'tofa-repo'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the API Docker image from repo root (Dockerfile.api expects backend/, requirements.txt)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.api'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'
      - '.'

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'
    waitFor: ['build-api']

  # Deploy to Cloud Run (Service: api)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'api'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '${PROJECT_ID}'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'PYTHONUNBUFFERED=1,PYTHONPATH=/app'
    waitFor: ['push-api']

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/api:latest'
